logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: trace
spring:
  datasource:
    url: jdbc:h2:mem:PUBLIC;MODE=MYSQL;CASE_INSENSITIVE_IDENTIFIERS=TRUE;
  sql:
    init:
      schema-locations: classpath:schema-sql.sql
      mode: always